name: greedymax-env
dependencies:
  - python=3.9.*
  - astropy
  - matplotlib
  - more-itertools
  - numpy=1.21.*
  - openpyxl
  - pytest
  - pytz
  - tabulate
  - scipy
  - coverage
  - requests
  - pandas
  - pip
  - pip:
    - omegaconf
    - python-dotenv
    - fastapi
    - strawberry-graphql[fastapi]
    - uvicorn[standard]
    - gql[all]
    - backoff
