collector:
  observation_classes: [SCIENCE, PROGCAL, PARTNERCAL]
  program_types: [Q, LP, FT, DD]
  time_slot_length: 1.0 # on minutes

optimizer:
  name: GREEDYMAX

server:
  port: 8000
  host: 0.0.0.0
