name: Deploy to Heroku Production app.

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build, Push and Release a Docker container to Heroku.
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        # Below you must provide variables for your Heroku app.

        # The email address associated with your Heroku account.
        # If you don't want to use repository secrets (which is recommended) you can do:
        # email: my.email@example.com
        heroku_email: ${{ secrets.HEROKU_EMAIL }}

        # Heroku API key associated with provided user's email.
        # Api Key is available under your Heroku account settings.
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

        # Name of the heroku application to which the build is to be sent.
        heroku_app_name: ${{ secrets.HEROKU_PRODUCTION_APP_NAME }}

        usedocker: true

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"