  name: Run Scripts
  on: push
  jobs:
    run:
      runs-on: ubuntu-latest
      timeout-minutes: 10

      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        # Setup Python (faster than using Python container)
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: $CONDA/bin/conda env update --file environment.yml --name base

        - name: Add $PYTHONPATH
          run: echo "PYTHONPATH=/home/runner/work/scheduler/scheduler" >> $GITHUB_ENV

        - name: Run Greedymax
          run: $CONDA/bin/python scheduler/scripts/run_greedymax.py

        - name: Run with Events
          run: $CONDA/bin/python scheduler/scripts/run_with_events.py
